### ISSUE TITLE
[HOUSEKEEPING] Develop template README for GitHub Actions and Cap Service Projects

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-projects#135]
### Description

We need to develop a tempalte README for GitHubActions and CapService Projects to have a comprehensive documentation to start from.

### Task List

- [ ] Create specific test project from projen-template-projects
- [ ] Create template  for READMES
- [ ] Add README to GitHubProject
- [ ] Add README to TemplateProject
- [ ] Add probably to .gitattributes
- [ ] Execute projen

**Comment by mvk-abs** [comment]
command is `projen new git_hub_action --from git+https://github.com/dxfrontier/projen-template-projects`
