### ISSUE TITLE
[HOUSEKEEPING] Move duplicate tests in base test area.

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-projects#136]
### Description

Centralizing duplicate test cases in a base area reduces redundancy, simplifies maintenance, and promotes reusability

### Task List

- [x] Create base test case area
- [x] Move duplicate test cases there
- [x] npm run build
