### ISSUE TITLE
[FEATURE]  Add CAP Service template

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-projects#138]
### Description

To ensure consistency, efficiency, and alignment with customer requirements, a structured project setup streamlines development, collaboration, and delivery.

### Task List

- [x] #139
- [x] Implement GitHub Tempaltes and tests
- [ ] Implement GitHub Workflows and tests
- [x] Check cliff.toml and tests
- [x] Check Husky and tests
- [x] Check vscode and tests
- [x] Check commitlint and tests
- [x] Implement devcontainer and tests
- [x] Implement eslint and tests
- [x] Check prettiefier and tests
- [x] Check .gitignore and tests
- [x] Add .gitattributes and tests
- [x] Check tsconfig and tests
- [x] Add SampleCode and tests
- [x] Implement package.json and tests

**Comment by mvk-abs** [comment]
@dragolea when you have a look into the [fco-accruals release workflow](https://github.com/Freudenberg-Co/fco-eoy-accruals/blob/dev/.github/workflows/release.yaml) then it seems that the newly created dxfrontier action is not yet user there  right?

**Comment by mvk-abs** [comment]
@dragolea having a look into the [fco-accruals package.json scripts](https://github.com/Freudenberg-Co/fco-eoy-accruals/blob/dev/package.json) it seems that we can clean up a the scripts are and dependencies. Let's have a look together on it.
