### ISSUE TITLE
[FEATURE] Add terraform template

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-projects#144]
### Description

To ensure consistency, efficiency, and alignment with terraform requirements, a structured project setup streamlines development, collaboration, and delivery.

### Task List

- [ ] Implement GitHub Templates and tests
- [ ] Implement GitHub Workflows and tests
- [ ] Check cliff.toml and tests
- [ ] Check Husky and tests
- [ ] Check vscode and tests
- [ ] Check commitlint and tests
- [ ] Implement devcontainer and tests
- [ ] Implement eslint and tests
- [ ] Check prettiefier and tests
- [ ] Check .gitignore and tests
- [ ] Add .gitattributes and tests
- [ ] Add .npmignore and tests
- [ ] Check tsconfig and tests
- [ ] Implement package.json settings and tests
