### ISSUE TITLE
[HOUSEKEEPING] Align test folders with project folders

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-projects#147]
### Description

Aligning the test folders supports clarity.

### Task List

- [x] Remove unnecessary test comments
- [x] Rename test folders according to project naming
- [x] npm run build

**Comment by mvk-abs** [comment]
this is a test for GitHub Teams integration issue

**Comment by mvk-abs** [comment]
just another test
